# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - 27017:27017

  backend:
    #build: .
    image: mikaelnilssonsweden/developer-test-backend
    restart: always
    ports: 
     - 8000:8080
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo



